id: koppeltaal
name: KoppeltaalIG
title: Koppeltaal 2.0 Implementation Guide (Minimal Package)
description: Koppeltaal 2.0 Implementation Guide - Minimal package without narratives for FHIR servers
canonical: http://koppeltaal.nl/fhir
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
status: draft
version: 1.4.5-beta.001
copyrightYear: 2024+
releaseLabel: ci-build
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#NL "Netherlands" # https://www.hl7.org/fhir/valueset-jurisdiction.html
language: en-US
publisher:
  name: VZVZ
  url: https://vzvz.nl

dependencies:
  nictiz.fhir.nl.r4.zib2020:
    version: 0.11.0-beta.1
    uri: http://simplifier.net/packages/nictiz.fhir.nl.r4.zib2020#0.11.0-beta.1
  nictiz.fhir.nl.r4.nl-core:
    version: 0.11.0-beta.1
    uri: http://simplifier.net/packages/nictiz.fhir.nl.r4.nl-core#0.11.0-beta.1
  vzvz.fhir.nl-vzvz-core:
    version: 0.2.2
    uri: https://simplifier.net/packages/vzvz.fhir.nl-vzvz-core@0.2.2

# No pages section for minimal package - we don't need HTML documentation

parameters: # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  apply-contact: false
  apply-jurisdiction: false
  apply-publisher: false
  excludettl: true
  pin-canonicals: pin-multiples
  path-resource:
    - input/resources
    - fsh-generated/resources
  special-url:
    - http://vzvz.nl/fhir/StructureDefinition/instantiates
    - http://vzvz.nl/fhir/ValueSet/endpoint-connection-type
    - http://vzvz.nl/fhir/ValueSet/koppeltaal-definition-topic
    - http://vzvz.nl/fhir/ValueSet/koppeltaal-task-code
    - urn:oid:2.16.840.1.113883.2.4.3.11.22.472
  special-url-base:
    - http://vzvz.nl/fhir/
  version-comparison: "n/a"
  usage-stats-opt-out: true
  # MINIMAL PACKAGE PARAMETERS - narratives disabled via IG Publisher CLI flag

# No menu section for minimal package - we don't need HTML menus

instanceOptions:
  manualSliceOrdering: true # true | false
  setMetaProfile: always # always | never | inline-only | standalone-only
  setId: always # always | standalone-only