name: Build (and Publish) FHIR packages to Simplifier

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      publish_reason:
        description: 'Reason for publishing'
        required: false
        default: 'Manual publish'

# Sets permissions
permissions:
  contents: read

jobs:
  publish:
    name: Publish FHIR Package to Simplifier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: koppeltaal-builder:latest

      - name: Run make publish
        env:
          FHIR_EMAIL: ${{ secrets.FHIR_EMAIL }}
          FHIR_PASSWORD: ${{ secrets.FHIR_PASSWORD }}
        run: |
          echo "Publishing FHIR package to Simplifier.net..."
          docker run \
            -v ${PWD}:/src \
            -e FHIR_EMAIL=${FHIR_EMAIL} \
            -e FHIR_PASSWORD=${FHIR_PASSWORD} \
            koppeltaal-builder:latest \
            publish

      - name: Summary
        if: always()
        run: |
          echo "## Publish Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "- **Reason**: ${{ github.event.inputs.publish_reason }}" >> $GITHUB_STEP_SUMMARY
          fi
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "- **Release**: ${{ github.event.release.tag_name }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
